namespace Altec.Api.Record.Printers;

public record PrinterInfo(
    string Model,
    string Serial,
    string Version,
    string CheckSum,
    int Dpi,
    string Mileage,
    int LabelCounter,
    int CutterCounter,
    string PrinterStatus,
    int CountryCode,
    int CodePage,
    string MacAddressNet,
    string IpAddressNet,
    string DnsName,
    double GapOffset,
    string SensorType,
    string PostPrint,
    int Speed,
    int Density,
    double LabelWidth,
    double LabelHeight,
    double GapSize,
    double BlineSize,
    int Direction,
    int Mirror,
    int Ribbon,
    int Offset,
    int ShiftX,
    int ShiftY,
    int ReferenceX,
    int ReferenceY,
    string HeadOpenSensor
);
